/** @type {import('@types/tailwindcss/tailwind-config').TailwindFontConfig } */
module.exports = {
  heading: [
    "var(--font-poppins)",
    "Poppins",
    '"Helvetica Neue"',
    "Helvetica",
    "Arial",
    '"Hiragino Sans"',
    "ヒラギノ角ゴシック",
    '"Hiragino Kaku Gothic ProN"',
    '"ヒラギノ角ゴ Pro W3"',
    "Roboto",
    "メイリオ",
    "Meiryo",
    '"ＭＳ Ｐゴシック"',
    "sans-serif",
  ],
  body: [
    "var(--font-lato)",
    "Lato",
    '"Helvetica Neue"',
    "Helvetica",
    '"Hiragino Sans"',
    '"ヒラギノ角ゴシック Pro"',
    '"Hiragino Kaku Gothic Pro"',
    "メイリオ",
    "Meiryo",
    "Osaka",
    '"ＭＳ Ｐゴシック"',
    '"MS PGothic"',
    "sans-serif",
  ],
};
